### ISSUE TITLE
Injective Asset Updates Automated

### ISSUE THREAD

**Issue by shane-moore** [cosmostation/chainlist#1364]
## Scope
- Created this issue to restart a convo as a follow-up to a previous [PR](https://github.com/cosmostation/chainlist/pull/974). The outcome of the closed PR was that Injective agreed to automate the addition of token metadata to your `chain/injective/assets.json` file. The automation script will live within injective's open-source `injective-ts` repo. 

## Sandbox environment
- forked `injective-ts` and added the script, which can be found [here](https://github.com/shane-moore/injective-ts/blob/test2/packages/sdk-ui-ts/src/services/cosmostation-tokens/tokens.ts)
- forked `cosmostation/chainlist` and ran the automation script from `injective-ts`, which opened a test [PR](https://github.com/shane-moore/chainlist/pull/7) to the forked `cosmostation/chainlist` repo

## Limitations of the script
- script will not replace any existing assets in the `chain/injective/assets.json` except for adding a `coingeckoId` if not present. Otherwise, the script ONLY appends new assets to `chain/injective/assets.json`
- cant guarantee the `origin_chain` will always have a value since we don't always have this on our end. Please check this when reviewing each PR to `cosmostation`, if it's a required field
- can't get `origin_type` as we do not store that info in `injective-ts` hardcoded assets list
- please check if `decimals` and `coingeckoId` are included on the new assets added in the PR to `cosmostation`, as we need those for defillama calc. else, please add if possible 
- cannot get image property
- script does not yet support the additional `ibc` or `bridge` token type properties of an asset for now as I'm trying to keep it simple. If needed, please add manually for now

## Todo
- please review the example [PR](https://github.com/shane-moore/chainlist/pull/7) and see if the file changes are formatted properly enough. I understand y'all may have to add additional properties on these automated PR's, but I hope it's at least better than having to do them all from scratch. Also, the first PR we make using this approach will obviously have many assets to add, like in example PR. But, all subsequent PR's should be much easier
- After the script is deemed to be producing adequate metadata for you guys, I will move the script over to our canonical `injective-ts` repo and use it to create a PR to the canonical `cosmostation/chainlist` repo
- happy to hear any thoughts or improvements y'all may have

**Comment by jeongeunlee1209** [comment]
Thank you for providing the follow-up on the Automation script to make the PR process easier.
Our development team has read the Issue opened on the chainlist and we are a bit skeptical about using the Automcaiton script because by looking at the limitation, script itself does not ensure to include all of the data that requires for us to operate products and services. 

Therefore, even with the automated processes, human verification is still required, making it necessary for us to regularly undertake this take. So, we would still like to ask the team to submit the PR on the assets that the team would like to add. For the urgent ones, like last time, please inform us through the telegram so that we can work on it as quickly as possible.
