### ISSUE TITLE
Tokens not displayed

### ISSUE THREAD

**Issue by Nonamet** [cosmostation/chainlist#1547]
Hi, after updated to new version of Cosmostation, I've sent HEART tokens Erc20 from another wallet to Erc20 Ethereum address on Cosmostation,but I can't see my tokens.
I've checked transaction and been 'Succesful'
Can you help me please?
![Screenshot_20240323-174156](https://github.com/cosmostation/chainlist/assets/164666560/cd16c198-6f0e-4e40-b9cb-62bb761f314e)
![Screenshot_20240320-222639](https://github.com/cosmostation/chainlist/assets/164666560/4e23e916-7b29-4698-b197-b6fbf940e793)

**Comment by jeongeunlee1209** [comment]
Thank you for using the Cosmostation product. By looking at the details that you provided, it seems like you transferred the $HEART token to the Ethereum network, not the HumansAI mainnet. Please follow the steps below so that you are able to activate the ERC-20 $HEART token on the Cosmostation mobile

1. From the Chains tab, please click on the telescope icon on top right. Then you should be able to see the wallet that you are able to add the Cosmostation mobile. From there, please select Ethereum and click confirm.
2.  Then Ethereum wallet should be visible. After this, please click on the Ethereum and click on the icon that has $ and the + icon. After that, please search $HEART token and click on confirm.

After following all of the steps above, then you should be able to see the $HEART token on the Ethereum network.
If you need further assistance on how to add $HEART token on the Ethereum network, please kindly send us an email to support@cosmostation.io

**Comment by Nonamet** [comment]
All done 😀🙏 Thanks again. Good bless you guys.
