### ISSUE TITLE
Chain Not show on mintscan

### ISSUE THREAD

**Issue by NodeNavigator** [cosmostation/chainlist#1602]
It's not a problem, it's something I'm worried about. I made a pull request for the **Shido chain** on April 5th, 2024, and it was successfully merged and closed. But I haven't seen my Shido chain on Mintscan yet. Is there a specific time when it will show up on Mintscan?

here is the Request link "https://github.com/cosmostation/chainlist/pull/1581"

**Comment by jeongeunlee1209** [comment]
Thank you for submitting PR to the Cosmostation chainlist. Please note that the PR that you submitted is for adding the information of the token and it does not list the token on mintscan. If you are still interested to be listed on the mintscan so that information like (Validator, Blocks, Transactions) to be displayed, please kindly reach out to [business@stamper.network](mailto:business@stamper.network). Our business team will kindly assist you on the process.
