### ISSUE TITLE
show validator proposal participation properly

### ISSUE THREAD

**Issue by patrickwieth** [cosmostation/chainlist#799]
Currently the proposal participation on mintscan is shown for all times even when a validator entered the active set later. So this gives values like 40/71 even though a validator participated in all proposals, but as a validator joined later, they were not able to participate in the earlier ones. 
This should be changed to a proportion reflecting the available proposals or a limited timeframe like 1 year, especially because it favors big validators and does not support decentralization as intended by enhancements of the active set.

This issue should actually be in the mintscan repo, but I guess it is private, so I can't open an issue there

**Comment by jeongeunlee1209** [comment]
Thank you so much for providing valuable feedback on the validator proposal participation on mintscan.

In order to keep the consistency and unity of the on-chain data in mintscan, we are using the denominator as the overall number of proposals that actually went to the 'voting period'. 

I will relay the information to the appropriate team so that they are able to find a way to enhance the display of the data.
